# SPDX-License-Identifier: Apache-2.0
---

- name: Configure - List required SAP Notes
  ansible.builtin.debug:
    var: __sap_general_preconfigure_sapnotes_versions | difference([''])

- name: Configure - Include configuration actions for required sapnotes
  ansible.builtin.include_tasks: "sapnote/{{ sap_note_line_item.number }}.yml"
  loop: "{{ __sap_general_preconfigure_sapnotes_versions | difference(['']) }}"
  loop_control:
    loop_var: sap_note_line_item
