# SPDX-License-Identifier: Apache-2.0
---

# Both sap_general_preconfigure_packages and __sap_general_preconfigure_min_pkgs are installed at same time.
- name: Ensure that the required packages are installed
  ansible.builtin.package:
    state: present
    name: "{{ sap_general_preconfigure_packages if not sap_general_preconfigure_min_package_check | bool
      else ((sap_general_preconfigure_packages | d([])) + (__sap_general_preconfigure_min_pkgs | d([])) | map(attribute='0') | unique) }}"


- name: Install minimum packages if required
  community.general.zypper:
    type: package
    name: '{{ line_item[0] }}>={{ line_item[1] }}'
    state: present
  loop: "{{ __sap_general_preconfigure_min_pkgs }}"
  loop_control:
    loop_var: line_item
  when:
    - sap_general_preconfigure_min_package_check|bool
    - __sap_general_preconfigure_min_pkgs | d([])


# Reason for noqa: Both yum and dnf support "state: latest"
- name: Ensure that the system is updated to the latest patchlevel # noqa package-latest
  ansible.builtin.package:
    state: latest
    name: "*"
  when: sap_general_preconfigure_update | bool


# Sapconf is present on: SLES 15
# Saptune is present on: SLES_SAP 15, SLES_SAP 16
- name: Install saptune if available
  ansible.builtin.include_tasks:
    file: generic/saptune_install.yml

- name: Takeover and enable saptune if available
  ansible.builtin.include_tasks:
    file: generic/saptune_takeover.yml


# Reason for noqa: The command to be executed might contain pipes
- name: Determine if the system needs to be restarted # noqa command-instead-of-shell
  ansible.builtin.shell: "zypper ps"
  register: __sap_general_preconfigure_register_needs_restarting
  ignore_errors: true
  changed_when: false
  check_mode: false

- name: Display the output of the reboot requirement check
  ansible.builtin.debug:
    var: __sap_general_preconfigure_register_needs_restarting


# sap_general_preconfigure_fact_reboot_required is used by follow up role: sap_hana_preconfigure
- name: Set the reboot requirement flag to false
  ansible.builtin.set_fact:
    sap_general_preconfigure_fact_reboot_required: false

- name: For needs-restarting - Set the flag that reboot is needed to apply changes
  ansible.builtin.set_fact:
    sap_general_preconfigure_fact_reboot_required: true
  when: __sap_general_preconfigure_register_needs_restarting is failed

- name: For needs-restarting - Display the content of sap_general_preconfigure_fact_reboot_required
  ansible.builtin.debug:
    var: sap_general_preconfigure_fact_reboot_required


- name: Call Reboot handler if necessary
  ansible.builtin.command: /bin/true
  notify: __sap_general_preconfigure_reboot_handler
  changed_when: true
  when:
    - __sap_general_preconfigure_register_needs_restarting is failed
      or __sap_general_preconfigure_register_needs_restarting.rc == 102
