# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 15

__sap_general_preconfigure_sapnotes_versions:
  # 2578899 - SUSE Linux Enterprise Server 15: Installation Note
  - { number: '2578899', version: '50' }
  # 2369910 - SAP Software on Linux: General information
  - { number: '2369910', version: '18' }

__sap_general_preconfigure_packages:
  # Mandatory patterns
  - patterns-server-enterprise-sap_server

  # Recommended packages
  - tcsh
  - psmisc

  # Additional packages
  - nfs-utils
  - bind-utils


__sap_general_preconfigure_min_pkgs: []
__sap_general_preconfigure_packagegroups:
__sap_general_preconfigure_envgroups:
__sap_general_preconfigure_kernel_parameters_default: []

# SLES_SAP is using saptune
__sap_general_preconfigure_use_saptune: true
