# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 15
# - SUSE Linux Enterprise Server 15
# - SUSE Linux Enterprise Server for SAP Applications 16
# - SUSE Linux Enterprise Server 16

__sap_general_preconfigure_sapnotes_versions:
  - '' # { number: '2369910', version: '18'}

__sap_general_preconfigure_packages:
  - uuidd
  - tcsh
  - psmisc
  - nfs-utils
  - bind-utils
  - hostname

__sap_general_preconfigure_min_pkgs:
__sap_general_preconfigure_packagegroups:
__sap_general_preconfigure_envgroups:
__sap_general_preconfigure_kernel_parameters_default:
