# SPDX-License-Identifier: Apache-2.0
---

# can be configured by tuned profile sap-hana, entry "transparent_hugepages=never" or "transparent_hugepages=madvise"
- name: Perform steps for setting transparent_hugepage to 'never' or 'madvise'
  when: not sap_hana_preconfigure_use_tuned or
        sap_hana_preconfigure_modify_grub_cmdline_linux or
        sap_hana_preconfigure_assert_all_config | d(false)
  block:

    - name: THP - Get contents of GRUB_CMDLINE_LINUX in /etc/default/grub
      ansible.builtin.command: grep GRUB_CMDLINE_LINUX /etc/default/grub
      register: __sap_hana_preconfigure_register_default_grub_cmdline_thp_assert
      changed_when: no

    - name: Assert that 'transparent_hugepage=never' is in GRUB_CMDLINE_LINUX in /etc/default/grub
      ansible.builtin.assert:
        that: "'transparent_hugepage=never' in __sap_hana_preconfigure_register_default_grub_cmdline_thp_assert.stdout"
        fail_msg: "FAIL: 'transparent_hugepage=never' is not in GRUB_CMDLINE_LINUX in /etc/default/grub!"
        success_msg: "PASS: 'transparent_hugepage=never' is in GRUB_CMDLINE_LINUX in /etc/default/grub."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors | d(false) }}"
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version == '7' or
          ansible_distribution_major_version == '8' or
          ansible_distribution_version == '9.0' or
          ansible_distribution_version == '9.1'

    - name: Assert that 'transparent_hugepage=madvise' is in GRUB_CMDLINE_LINUX in /etc/default/grub
      ansible.builtin.assert:
        that: "'transparent_hugepage=madvise' in __sap_hana_preconfigure_register_default_grub_cmdline_thp_assert.stdout"
        fail_msg: "FAIL: 'transparent_hugepage=madvise' is not in GRUB_CMDLINE_LINUX in /etc/default/grub!"
        success_msg: "PASS: 'transparent_hugepage=madvise' is in GRUB_CMDLINE_LINUX in /etc/default/grub."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors | d(false) }}"
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version == '9' and
            __sap_hana_preconfigure_fact_ansible_distribution_minor_version | int >= 2

    - name: THP - Get contents of /proc/cmdline
      ansible.builtin.command: cat /proc/cmdline
      register: __sap_hana_preconfigure_register_proc_cmdline_thp_assert
      changed_when: no

    - name: Assert that 'transparent_hugepage=never' is in /proc/cmdline
      ansible.builtin.assert:
        that: "'transparent_hugepage=never' in __sap_hana_preconfigure_register_proc_cmdline_thp_assert.stdout"
        fail_msg: "FAIL: 'transparent_hugepage=never' is not in /proc/cmdline!"
        success_msg: "PASS: 'transparent_hugepage=never' is in /proc/cmdline."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors | d(false) }}"
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version == '7' or
          ansible_distribution_major_version == '8' or
          ansible_distribution_version == '9.0' or
          ansible_distribution_version == '9.1'

    - name: Assert that 'transparent_hugepage=madvise' is in /proc/cmdline
      ansible.builtin.assert:
        that: "'transparent_hugepage=madvise' in __sap_hana_preconfigure_register_proc_cmdline_thp_assert.stdout"
        fail_msg: "FAIL: 'transparent_hugepage=madvise' is not in /proc/cmdline!"
        success_msg: "PASS: 'transparent_hugepage=madvise' is in /proc/cmdline."
      ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors | d(false) }}"
      when:
        - ansible_distribution == 'RedHat'
        - ansible_distribution_major_version == '9' and
            __sap_hana_preconfigure_fact_ansible_distribution_minor_version | int >= 2
