# SPDX-License-Identifier: Apache-2.0
---

- name: Get boot command line
  ansible.builtin.slurp:
    src: /proc/cmdline
  register: __sap_hana_preconfigure_register_proc_cmdline_thp

- name: Set THP to 'never' at boot time
  ansible.builtin.command: /bin/true
  notify: __sap_hana_preconfigure_grubby_thp_never_handler
  changed_when: true
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '8' or
      ansible_distribution_version == '9.0' or
      ansible_distribution_version == '9.1'
    - not ( __sap_hana_preconfigure_register_proc_cmdline_thp['content'] | b64decode | regex_findall('transparent_hugepage=never') )
  tags: grubconfig

- name: Set THP to 'madvise' at boot time
  ansible.builtin.command: /bin/true
  notify: __sap_hana_preconfigure_grubby_thp_madvise_handler
  changed_when: true
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '9' and
        __sap_hana_preconfigure_fact_ansible_distribution_minor_version | int >= 2
    - not ( __sap_hana_preconfigure_register_proc_cmdline_thp['content'] | b64decode | regex_findall('transparent_hugepage=madvise') )
  tags: grubconfig

- name: Configure - Get initial status of THP
  ansible.builtin.command: cat /sys/kernel/mm/transparent_hugepage/enabled
  register: __sap_hana_preconfigure_register_thp_status_before
  changed_when: false

- name: Set THP to 'never' on the running system
  ansible.builtin.shell: echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled
  changed_when: true
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '8' or
      ansible_distribution_version == '9.0' or
      ansible_distribution_version == '9.1'
    - __sap_hana_preconfigure_register_thp_status_before.stdout.split('[')[1].split(']')[0] != 'never'

- name: Set THP to 'madvise' on the running system
  ansible.builtin.shell: echo 'madvise' > /sys/kernel/mm/transparent_hugepage/enabled
  changed_when: true
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '9' and
        __sap_hana_preconfigure_fact_ansible_distribution_minor_version | int >= 2
    - __sap_hana_preconfigure_register_thp_status_before.stdout.split('[')[1].split(']')[0] != 'madvise'

- name: Configure - Get the status of THP
  ansible.builtin.command: cat /sys/kernel/mm/transparent_hugepage/enabled
  register: __sap_hana_preconfigure_register_thp_status
  ignore_errors: true
  changed_when: false

- name: Display the status of THP
  ansible.builtin.debug:
    var: __sap_hana_preconfigure_register_thp_status.stdout_lines, __sap_hana_preconfigure_register_thp_status.stderr_lines
