# SPDX-License-Identifier: Apache-2.0
---
- name: Assert - Display SAP note number 2369910 and its version
  ansible.builtin.debug:
    msg: "SAP note {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2369910$') | first).number }}
          (version {{ (__sap_general_preconfigure_sapnotes_versions | selectattr('number', 'match', '^2369910$') | first).version }}): Configure RHEL 7"
  tags:
    - always

## STEP 3.1 -- System Language
- name: Step 3.1 - Check if English Languge is installed
  tags:
    - sap_general_preconfigure_2369910
    - sap_general_preconfigure_2369910_03
  block:
    - name: Get list of installed locales
      ansible.builtin.command: locale -a
      changed_when: false
      register: __sap_general_preconfigure_locales_installed

    - name: Ensure English langpacks are available on RHEL
      when: locale_list.stdout_lines | select('match', '^en_') | list | length == 0
    
    - name: Check if English locale is installed
      ansible.builtin.assert:
        that:
          # "'en_US.UTF-8' in __sap_general_preconfigure_locales_installed.stdout"
          - locale_list.stdout_lines | select('match', '^en_') | list | length > 0
        fail_msg: "FAIL: No English locale installed. please install English locale"
        success_msg: "PASS: English locale is installed"

- name: Step 3.1 - Check if English Languge is Default locale
  tags:
    - sap_general_preconfigure_2369910
    - sap_general_preconfigure_2369910_03
  block:
    - name: Check if current default locale is English
      ansible.builtin.command: grep "^LANG=en_" /etc/locale.conf
      changed_when: false
      register: __sap_general_preconfigure_current_default_locale

    - name: Assert that __sap_general_preconfigure_current_default_locale output is not empty
      ansible.builtin.assert:
        that:
          - __sap_general_preconfigure_current_default_locale.stdout_lines | length > 0
        fail_msg: "FAIL: English is not set as default locale"
        success_msg: "PASS: English default locale is set"

