# SPDX-License-Identifier: Apache-2.0
---
# Variables specific to following versions:
# - SUSE Linux Enterprise Server for SAP Applications 16

__sap_netweaver_preconfigure_sapnotes_versions: []

__sap_netweaver_preconfigure_packages:
  # Mandatory patterns
  - patterns-sap-APP

  # Recommended packages
  - tcsh
  - psmisc
  - acl
  - uuidd

  # 2578899 is not updated for SLES 16 yet.
  - uuidd
  - sysstat
  - sysctl-logger

  # 3139184 - Linux: systemd integration for sapstartsrv and SAP Host Agent
  - polkit

  # Recommended for System monitoring
  - cpupower
  - libcpupower1
  - libsensors4

  # Additional packages
  - nfs-utils
  - bind-utils
  - procmail
  - libltdl7


# SLES_SAP is using saptune, but SLES is using sapconf.
# Default value true runs saptune, but installation.yml auto-detects base product and adjusts.
__sap_netweaver_preconfigure_use_saptune: true
