# SPDX-License-Identifier: Apache-2.0
---

- name: Get list of what provides packages  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: "rpm -q --whatprovides {{ item }}"
  register: __sap_hana_preconfigure_register_whatprovides
  changed_when: false
  loop: "{{ __sap_hana_preconfigure_packages_2684254 }}"

- name: Assert that all required packages are installed
  ansible.builtin.assert:
    that: item in ansible_facts.packages
      or __sap_hana_preconfigure_register_whatprovides.results | selectattr('item', 'equalto', item) | map(attribute='rc') | first == 0
    fail_msg: "FAIL: Package '{{ item }}' is not installed!"
    success_msg: "PASS: Package '{{ item }}' is installed."
  loop: "{{ __sap_hana_preconfigure_packages_2684254 }}"
  ignore_errors: "{{ sap_hana_preconfigure_assert_ignore_errors | d(false) }}"
