# SPDX-License-Identifier: Apache-2.0
---
# If this is a cluster node on Azure, we need to override to disable tcp timestamps, reuse and recycle.
# This can be done by copying the sapnote file 2382421 from /usr/share/saptune/notes to /etc/saptune/override
# The value can then override in the in the new file
# net.ipv4.tcp_tw_recycle = 0 was removed as it is not relevant for SLES 15+

- name: Disable TCP timestamps, recycle & reuse
  ansible.builtin.blockinfile:
    path: /etc/saptune/override/2382421
    create: true
    backup: true
    owner: root
    group: root
    mode: '0640'
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: |
      [sysctl]
      net.ipv4.tcp_timestamps = 0
      net.ipv4.tcp_tw_reuse = 0
  when:
    - sap_hana_preconfigure_saptune_azure
    - __sap_hana_preconfigure_use_saptune


- name: Apply saptune solution
  when: __sap_hana_preconfigure_use_saptune
  block:
    - name: Discover active solution
      ansible.builtin.command:
        cmd: saptune solution enabled
      register: __sap_hana_preconfigure_register_saptune_status
      changed_when: false

    - name: Set fact for active solution
      ansible.builtin.set_fact:
        # Capture the first block on none whitespace
        __sap_hana_preconfigure_register_solution_configured:
          "{{ (__sap_hana_preconfigure_register_saptune_status.stdout | regex_search('(\\S+)', '\\1'))[0] | default('NONE') }}"


    - name: Revert solution when different to sap_hana_preconfigure_saptune_solution
      ansible.builtin.command:
        cmd: "saptune solution revert {{ __sap_hana_preconfigure_register_solution_configured }}"
      changed_when: true
      when:
        - __sap_hana_preconfigure_register_solution_configured != 'NONE'
        - __sap_hana_preconfigure_register_solution_configured != sap_hana_preconfigure_saptune_solution


    - name: Verify saptune solution
      ansible.builtin.command:
        cmd: "saptune solution verify {{ sap_hana_preconfigure_saptune_solution }}"
      register: __sap_hana_preconfigure_register_saptune_verify
      changed_when: false
      failed_when: false
      when:
        - __sap_hana_preconfigure_register_solution_configured == sap_hana_preconfigure_saptune_solution


    - name: Ensure saptune solution is applied
      ansible.builtin.command:
        cmd: "saptune solution apply {{ sap_hana_preconfigure_saptune_solution }}"
      changed_when: true
      when:
        - __sap_hana_preconfigure_register_solution_configured != sap_hana_preconfigure_saptune_solution
          or __sap_hana_preconfigure_register_saptune_verify.rc != 0


    - name: Ensure solution was successful
      ansible.builtin.command:
        cmd: "saptune solution verify {{ sap_hana_preconfigure_saptune_solution }}"
      changed_when: false


- name: Configure - Include configuration actions for required sapnotes
  ansible.builtin.include_tasks: "sapnote/{{ sap_note_line_item.number }}.yml"
  loop: "{{ __sap_hana_preconfigure_sapnotes_versions | difference(['']) }}"
  loop_control:
    loop_var: sap_note_line_item
