---
# The following directories are appended to the 'nfs_path' of the '/usr/sap' storage
# definition.
# Therefore, the /usr/sap prefix must be left out of the listed path items.
__sap_ha_pacemaker_cluster_wdp_filesystems:
  - "{{ sap_ha_pacemaker_cluster_wdp_sid }}/W{{ sap_ha_pacemaker_cluster_wdp_instance_nr }}"


# List of WDP profile names.
# Used in tasks/configure_nwas_postinstallation.yml for sap_cluster_connector setup.
__sap_ha_pacemaker_cluster_wdp_profile_paths:
  - "{{ sap_ha_pacemaker_cluster_wdp_sapinstance_start_profile_string }}"
