# SPDX-License-Identifier: Apache-2.0
---

- name: Apply saptune solution
  when: __sap_netweaver_preconfigure_use_saptune
  block:
    - name: Discover active solution
      ansible.builtin.command:
        cmd: saptune solution enabled
      register: __sap_netweaver_preconfigure_register_saptune_status
      changed_when: false

    - name: Set fact for active solution
      ansible.builtin.set_fact:
        # Capture the first block on none whitespace
        __sap_netweaver_preconfigure_register_solution_configured:
          "{{ (__sap_netweaver_preconfigure_register_saptune_status.stdout | regex_search('(\\S+)', '\\1'))[0] | default('NONE') }}"


    - name: Revert solution when different to sap_netweaver_preconfigure_saptune_solution
      ansible.builtin.command:
        cmd: "saptune solution revert {{ __sap_netweaver_preconfigure_register_solution_configured }}"
      changed_when: true
      when:
        - __sap_netweaver_preconfigure_register_solution_configured != 'NONE'
        - __sap_netweaver_preconfigure_register_solution_configured != sap_netweaver_preconfigure_saptune_solution


    - name: Verify saptune solution
      ansible.builtin.command:
        cmd: "saptune solution verify {{ sap_netweaver_preconfigure_saptune_solution }}"
      register: __sap_netweaver_preconfigure_register_saptune_verify
      changed_when: false
      failed_when: false
      when:
        - __sap_netweaver_preconfigure_register_solution_configured == sap_netweaver_preconfigure_saptune_solution


    - name: Ensure saptune solution is applied
      ansible.builtin.command:
        cmd: "saptune solution apply {{ sap_netweaver_preconfigure_saptune_solution }}"
      changed_when: true
      when:
        - __sap_netweaver_preconfigure_register_solution_configured != sap_netweaver_preconfigure_saptune_solution
          or __sap_netweaver_preconfigure_register_saptune_verify.rc != 0


    - name: Ensure solution was successful
      ansible.builtin.command:
        cmd: "saptune solution verify {{ sap_netweaver_preconfigure_saptune_solution }}"
      changed_when: false


- name: Warn if not enough swap space is configured
  ansible.builtin.fail:
    msg: "The system has only {{ ansible_swaptotal_mb }} MB of swap space configured,
      which is less than the minimum required amount of {{ sap_netweaver_preconfigure_min_swap_space_mb
       }} MB for SAP NetWeaver!"
  ignore_errors: true
  when:
    - ansible_swaptotal_mb < sap_netweaver_preconfigure_min_swap_space_mb|int
    - not sap_netweaver_preconfigure_fail_if_not_enough_swap_space_configured|d(true)

- name: Fail if not enough swap space is configured
  ansible.builtin.fail:
    msg: "The system has only {{ ansible_swaptotal_mb }} MB of swap space configured,
      which is less than the minimum required amount of {{ sap_netweaver_preconfigure_min_swap_space_mb
       }} MB for SAP NetWeaver!"
  when:
    - ansible_swaptotal_mb < sap_netweaver_preconfigure_min_swap_space_mb|int
    - sap_netweaver_preconfigure_fail_if_not_enough_swap_space_configured|d(true)
