# SPDX-License-Identifier: Apache-2.0
---

# Detect Product ID
- name: SAP SWPM Pre Install - Detect Product ID from inifile
  ansible.builtin.command: |
    awk 'BEGIN{IGNORECASE=1;a=0}
      /Product ID/&&a==0{a=1; gsub ("#", ""); gsub ("\047", ""); product_id=$NF}
      END{print product_id}' {{ sap_swpm_tmpdir_local.path }}/inifile.params
  delegate_to: localhost
  register: sap_swpm_inifile_product_id_detect
  changed_when: false

- name: SAP SWPM Pre Install - Set SAP product ID
  ansible.builtin.set_fact:
    sap_swpm_product_catalog_id: "{{ sap_swpm_inifile_product_id_detect.stdout }}"

# Detect and set Software Path
- name: SAP SWPM Pre Install - Detect Software Path from inifile
  ansible.builtin.command: |
    awk '!/^#/&&/archives.downloadBasket/{print $3}' {{ sap_swpm_tmpdir_local.path }}/inifile.params
  delegate_to: localhost
  register: sap_swpm_inifile_software_path_detect
  changed_when: false

- name: SAP SWPM Pre Install - Set Software Path
  ansible.builtin.set_fact:
    sap_swpm_software_path: "{{ sap_swpm_inifile_software_path_detect.stdout }}"

# Detect and set SID
- name: SAP SWPM Pre Install - Detect SID from inifile
  ansible.builtin.command: |
    awk '!/^#/&&/NW_GetSidNoProfiles.sid/{print $3}' {{ sap_swpm_tmpdir_local.path }}/inifile.params
  delegate_to: localhost
  register: sap_swpm_inifile_sid_detect
  changed_when: false

- name: SAP SWPM Pre Install - Set SID from inifile
  ansible.builtin.set_fact:
    sap_swpm_sid: "{{ sap_swpm_inifile_sid_detect.stdout }}"

# Detect FQDN
- name: SAP SWPM Pre Install - Detect FQDN from inifile
  ansible.builtin.command: |
    awk '!/^#/&&/NW_getFQDN.FQDN/{print $3}' {{ sap_swpm_tmpdir_local.path }}/inifile.params
  delegate_to: localhost
  register: sap_swpm_inifile_fqdn_detect
  changed_when: false

- name: SAP SWPM Pre Install - Set FQDN
  ansible.builtin.set_fact:
    sap_swpm_fqdn: "{{ sap_swpm_inifile_fqdn_detect.stdout }}"
