# SPDX-License-Identifier: Apache-2.0
---

# The following task is used for checking if an inifile exists on the managed node
- name: SAP SWPM Pre Install - Ensure the sapinst inifile directory '{{ sap_swpm_inifile_directory }}' exists on the managed node
  ansible.builtin.file:
    path: "{{ sap_swpm_inifile_directory }}"
    state: directory
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: SAP SWPM Pre Install - Check if file '{{ sap_swpm_inifile_directory }}/inifile.params' exists on the managed node
  ansible.builtin.stat:
    path: "{{ sap_swpm_inifile_directory }}/inifile.params"
  check_mode: no
  register: __sap_swpm_register_stat_sapinst_inifile

- name: SAP SWPM Pre Install - Try using existing SWPM inifile 'inifile.params'
  when: __sap_swpm_register_stat_sapinst_inifile.stat.exists
  block:

    - name: SAP SWPM Pre Install, use existing inifile - Notify about existing sapinst inifile on the managed node
      ansible.builtin.debug:
        msg: "INFO: Using existing sapinst inifile '{{ sap_swpm_inifile_directory }}/inifile.params'."

# Note: Attempting to fetch and store into sap_swpm_tmpdir_local.path results in a 'Permission denied' error.
# So we are using 'slurp' and 'copy' for this purpose.
    - name: SAP SWPM Pre Install, use existing inifile - Slurp the remote 'inifile.params' for copying to control node
      ansible.builtin.slurp:
        src: "{{ sap_swpm_inifile_directory }}/inifile.params"
      register: sap_swpm_slurped_remote_inifile

    - name: SAP SWPM Pre Install, existing inifile - Copy 'inifile.params' to the control node
      ansible.builtin.copy:
        content: "{{ sap_swpm_slurped_remote_inifile['content'] | b64decode }}"
        dest: "{{ sap_swpm_tmpdir_local.path }}/inifile.params"
        owner: 'root'
        group: 'root'
        mode: '0640'
      delegate_to: localhost

# Now we need to confirm that des25 is not in the inifile
    - name: SAP SWPM Pre Install, use existing inifile - Search inifile for for des25
      ansible.builtin.shell: |
        set -o pipefail && awk 'BEGIN{a=0}!/^#/&&/des25\(/{a++}END{print a}' {{ sap_swpm_tmpdir_local.path }}/inifile.params
      delegate_to: localhost
      register: sap_swpm_inifile_count_des25
      changed_when: false

    - name: SAP SWPM Pre Install, use existing inifile - Ensure that des25 is not present in inifile
      ansible.builtin.fail:
        msg:
          - "Inifile '{{ sap_swpm_inifile_directory }}/inifile.params' cannot be reused because it contains des25 encrypted data."
          - "See also SAP notes 2609804."
      when: sap_swpm_inifile_count_des25.stdout != '0'

# We are creating the inifile dynamically in one of the two cases:
# 1 - The tag sap_swpm_generate_inifile is specified
# 2 - There is no file 'inifile.params' available in 'sap_swpm_inifile_directory'
# Prerequisite: Role parameter 'sap_swpm_product_catalog_id' is defined
- name: SAP SWPM Pre Install, create inifile - Create the SWPM inifile 'inifile.params' dynamically
  when: "'sap_swpm_generate_inifile' in ansible_run_tags or (not __sap_swpm_register_stat_sapinst_inifile.stat.exists)"
  block:

    - name: SAP SWPM Pre Install - Ensure role parameter 'sap_swpm_product_catalog_id' is defined
      ansible.builtin.fail:
        msg:
          - "Role parameter 'sap_swpm_product_catalog_id' is not defined, so certain inifile entries cannot be determined."
          - "Remediation: Define the role parameter 'sap_swpm_product_catalog_id' in your playbook or inventory and re-run the playbook."
      when: sap_swpm_product_catalog_id is not defined

# 3 tasks for setting password Facts, required for the template:
    - name: SAP SWPM Pre Install - Set password facts when ABAP
      ansible.builtin.set_fact:
        sap_swpm_db_schema: "{{ sap_swpm_db_schema_abap }}"
        sap_swpm_db_schema_password: "{{ sap_swpm_db_schema_abap_password }}"
      when: "'ABAP' in sap_swpm_product_catalog_id"

    - name: SAP SWPM Pre Install - Set password facts when Java
      ansible.builtin.set_fact:
        sap_swpm_db_schema: "{{ sap_swpm_db_schema_java }}"
        sap_swpm_db_schema_password: "{{ sap_swpm_db_schema_java_password }}"
      when: "'Java' in sap_swpm_product_catalog_id"

    - name: SAP SWPM Pre Install - Set other user passwords using master password
      ansible.builtin.set_fact:
        sap_swpm_sapadm_password: "{{ sap_swpm_master_password }}"
        sap_swpm_sap_sidadm_password: "{{ sap_swpm_master_password }}"
        sap_swpm_diagnostics_agent_password: "{{ sap_swpm_master_password }}"

# Generate inifile.params, step 1: Process SWPM Configfile template locally for creating inifile.params
    - name: SAP SWPM Pre Install, create inifile - Process SWPM inifile template for for creating 'inifile.params'
      ansible.builtin.template:
        src: "{{ role_path }}/templates/inifile_params.j2"
        dest: "{{ sap_swpm_tmpdir_local.path }}/inifile.params"
        owner: 'root'
        group: 'root'
        mode: '0640'
      delegate_to: localhost
      when:
        - sap_swpm_inifile_sections_list is defined
        - sap_swpm_inifile_sections_list | length > 0
      tags: sap_swpm_generate_inifile

# Generate inifile.params, step 2: Use any entries from sap_swpm_inifile_parameters_dict
    - name: SAP SWPM Pre Install, create inifile - Use any 'inifile.params' entries from sap_swpm_inifile_parameters_dict
      ansible.builtin.lineinfile:
        path: "{{ sap_swpm_tmpdir_local.path }}/inifile.params"
        create: true
        state: present
        line: "{{ sap_swpm_line_item.key }} = {{ sap_swpm_line_item.value }}"
        regexp: "^{{ sap_swpm_line_item.key }}[\\s]*=[\\s]*.*"
        owner: 'root'
        group: 'root'
        mode: '0640'
      loop: "{{ sap_swpm_inifile_parameters_dict | dict2items }}"
      loop_control:
        loop_var: sap_swpm_line_item
      register: replace_result
      delegate_to: localhost
      when:
        - sap_swpm_inifile_parameters_dict is defined
        - sap_swpm_inifile_parameters_dict | length > 0
      tags: sap_swpm_generate_inifile

- name: SAP SWPM Pre Install - Display the path of the local 'inifile.params'
  ansible.builtin.debug:
    msg: "The local inifile.params is: '{{ sap_swpm_tmpdir_local.path }}/inifile.params'"
  tags: sap_swpm_generate_inifile

- name: SAP SWPM Pre Install - Detect Variables
  ansible.builtin.include_tasks:
    file: detect_variables_from_inifile.yml

- name: SAP SWPM Pre Install - Slurp the local 'inifile.params' for copying to managed node
  ansible.builtin.slurp:
    src: "{{ sap_swpm_tmpdir_local.path }}/inifile.params"
  register: sap_swpm_slurped_local_inifile
  delegate_to: localhost

- name: SAP SWPM Pre Install - Copy 'inifile.params' to the managed node
  ansible.builtin.copy:
    content: "{{ sap_swpm_slurped_local_inifile['content'] | b64decode }}"
    dest: "{{ sap_swpm_tmpdir.path }}/inifile.params"
    owner: 'root'
    group: 'root'
    mode: '0640'

- name: SAP SWPM Pre Install - Display the path of the remote 'inifile.params'
  ansible.builtin.debug:
    msg: "The local inifile.params has been copied to: '{{ sap_swpm_tmpdir.path }}/inifile.params'"
